feat: Support Max Parameters and Properties
mparticle-integrations/mparticle-android-integration-google-analytics-firebase-ga4 pull request #58
Opened 2023-05-08 16:39 UTC by BrandonStalnaker

## Summary
 - GA places limitations on the number of parameters and properties allowed on their events and items.

 ## Testing Plan
 - Tested manually and with unit tests

 ## Reference Issue (For mParticle employees only.  Ignore if you are an outside contributor)
 - Closes https://go.mparticle.com/work/SQDSDKS-5278

2023-05-10 14:11 UTC, BrandonStalnaker commented
Seems like the tests are only failing on development so I'm not sure what's going on. Any idea Mark?

2023-05-12 18:08 UTC, einsteinx2 requested changes
Looks like some existing unit tests failed with this change.

2023-05-15 16:07 UTC, BrandonStalnaker commented on src/main/kotlin/com/mparticle/kits/GoogleAnalyticsFirebaseGA4Kit.kt
> +                if (bundle.keySet().size > eventMaxParameterProperty) {
Extracted the code to its own function. Any idea what's going on around the tests? The java.lang.NoSuchMethodError doesn't make any sense to me sense it compiles successfully. Seems like a test specific issue?

2023-05-15 20:06 UTC, markvdouw commented on src/main/kotlin/com/mparticle/kits/GoogleAnalyticsFirebaseGA4Kit.kt
> +                if (bundle.keySet().size > eventMaxParameterProperty) {
So strange it doesnt make sense!

2023-05-15 20:07 UTC, markvdouw approved these changes
LGTM

2023-05-16 14:28 UTC, merged