Fix: Update allowable character limits and number of attributes for GA360
mparticle-integrations/mparticle-android-integration-google-analytics-firebase-ga4 pull request #85
Opened 2024-02-26 15:24 UTC by Mansi-mParticle

## Instructions
 1. PR target branch should be against `development`
 2. PR title name should follow this format: https://github.com/mParticle/mparticle-workflows/blob/main/.github/workflows/pr-title-check.yml
 3. PR branch prefix should follow this format: https://github.com/mParticle/mparticle-workflows/blob/main/.github/workflows/pr-branch-check-name.yml

 ## Summary
 - Change GA4 Limits to Enterprise Plan Standard
 
 ## Testing Plan
 No, we do not have access to a GA360 account, PR is just a change in the value of max attributes allowed.
 - {explain how this has been tested, and what, if any, additional testing should be done}

 ## Reference Issue (For mParticle employees only.  Ignore if you are an outside contributor)
 - Closes https://go.mparticle.com/work/SQDSDKS-6134

2024-02-26 22:23 UTC, rmi22186 requested changes
lgtm!  but 2 quick comments

2024-02-26 22:23 UTC, rmi22186 commented on src/main/kotlin/com/mparticle/kits/GoogleAnalyticsFirebaseGA4Kit.kt
> +        // Following limits are based off Google Analytics 360 limits, docs here "https://support.google.com/analytics/answer/11202874?sjid=14644072134282618832-NA#limits"
Remove this comment.  Putting it once on line 691 is sufficient.

2024-02-26 22:23 UTC, rmi22186 commented on src/test/kotlin/com/mparticle/kits/GoogleAnalyticsFirebaseGA4KitTest.kt
> +            }*/
Is there a reason this is commented out?

2024-02-26 22:56 UTC, rmi22186 approved these changes

2024-02-27 00:45 UTC, samdozor approved these changes

2024-02-27 16:32 UTC, BrandonStalnaker approved these changes
LGTM

2024-02-27 16:38 UTC, merged